openapi: 3.0.0
info:
  title: User Management API
  description: API for managing user profiles, authentication, and breeder profiles.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /profile:
    get:
      summary: Get user profile
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  UserId:
                    type: integer
                  Username:
                    type: string
                  FirstName:
                    type: string
                  LastName:
                    type: string
                  Phone:
                    type: string
                  Email:
                    type: string
                  Balance:
                    type: number
        '500':
          description: Internal server error

  /register:
    post:
      summary: Register a new user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                phone:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request (Username/Email/Phone already exists)
        '500':
          description: Internal server error

  /login:
    post:
      summary: Login a user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized (Incorrect credentials)
        '500':
          description: Internal server error

  /logout:
    post:
      summary: Logout a user
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful

  /forgot-password:
    post:
      summary: Forgot password
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password reset link sent
        '404':
          description: User not found
        '500':
          description: Internal server error

  /reset-password/{token}:
    patch:
      summary: Reset password
      tags:
        - User
      parameters:
        - in: path
          name: token
          schema:
            type: string
          required: true
          description: Reset token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        '201':
          description: Password reset successfully
        '401':
          description: Invalid or expired token
        '500':
          description: Internal server error

  /update-password:
    patch:
      summary: Update user password
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        '201':
          description: Password updated successfully
        '500':
          description: Internal server error

  /update-profile:
    patch:
      summary: Update user profile
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                phone:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User updated successfully
        '500':
          description: Internal server error

  /delete:
    delete:
      summary: Delete user account
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '201':
          description: User deleted successfully
        '500':
          description: Internal server error

  /manage/profile:
    get:
      summary: Get all profiles
      tags:
        - Admin
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profiles retrieved successfully
        '404':
          description: Users not found
        '500':
          description: Internal server error
    post:
      summary: Create a user profile (Admin only)
      tags:
        - Admin
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                phone:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User profile created successfully
        '400':
          description: Bad request (Username/Email/Phone already exists)
        '500':
          description: Internal server error

  /manage/profile/{id}:
    get:
      summary: Get profile by ID
      tags:
        - Admin
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User profile retrieved successfully
        '404':
          description: User not found
        '500':
          description: Internal server error
    patch:
      summary: Update user profile by ID
      tags:
        - Admin
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                phone:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User profile updated successfully
        '500':
          description: Internal server error
    delete:
      summary: Delete user profile by ID
      tags:
        - Admin
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User profile deleted successfully
        '500':
          description: Internal server error

  /manage/breeder/profile:
    get:
      summary: Get all breeder profiles
      tags:
        - Admin
      responses:
        '200':
          description: Breeder profiles retrieved successfully
        '404':
          description: Breeder profiles not found
        '500':
          description: Internal server error

  /manage/breeder/profile/{id}:
    get:
      summary: Get breeder profile by ID
      tags:
        - Admin
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Breeder profile retrieved successfully
        '404':
          description: Breeder profile not found
        '500':
          description: Internal server error
    patch:
      summary: Update breeder profile by ID
      tags:
        - Admin
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                farmName:
                  type: string
                location:
                  type: string
                contact:
                  type: string
      responses:
        '201':
          description: Breeder profile updated successfully
        '500':
          description: Internal server error
    delete:
      summary: Delete breeder profile by ID
      tags:
        - Admin
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Breeder profile deleted successfully
        '500':
          description: Internal server error
