openapi: 3.0.0
info:
  title: User and Breeder Management API
  version: 1.0.0
  description: API for managing users and breeders in the system.
paths:
  /profile:
    get:
      summary: Get the current user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully.
        '401':
          description: Unauthorized access.
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                phone:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User created successfully.
        '400':
          description: User already exists.
  /login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful.
        '401':
          description: Invalid credentials or user is not active.
  /logout:
    post:
      summary: Logout user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful.
  /update-password:
    patch:
      summary: Update user password
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        '201':
          description: Password updated successfully.
  /update-profile:
    patch:
      summary: Update user profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                phone:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User profile updated successfully.
  /delete:
    delete:
      summary: Deactivate user account
      security:
        - bearerAuth: []
      responses:
        '201':
          description: User deactivated successfully.
  /breeder/profile:
    get:
      summary: Get the breeder profile of the current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Breeder profile retrieved successfully.
  /manage/profile:
    get:
      summary: Get all user profiles
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of all user profiles.
    post:
      summary: Create a new user profile (admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                userRoleId:
                  type: integer
      responses:
        '201':
          description: User profile created successfully.
  /manage/profile/{id}:
    get:
      summary: Get a user profile by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User profile retrieved successfully.
    patch:
      summary: Update a user profile by ID
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                userRoleId:
                  type: integer
      responses:
        '201':
          description: User profile updated successfully.
    delete:
      summary: Delete a user profile by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User profile deleted successfully.
  /manage/breeder/profile:
    get:
      summary: Get all breeder profiles
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of all breeder profiles.
  /manage/breeder/profile/{id}:
    get:
      summary: Get a breeder profile by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Breeder profile retrieved successfully.
    patch:
      summary: Update a breeder profile by ID
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                farmName:
                  type: string
                location:
                  type: string
                contact:
                  type: string
      responses:
        '201':
          description: Breeder profile updated successfully.
    delete:
      summary: Delete a breeder profile by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Breeder profile deleted successfully.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
